version: "3"

services:
  framework:
    container_name: framework
    build: .
    volumes:
      - c:/Users/gltop/Desktop/framework:/usr/src/app
      - /usr/src/app/vendor
    links:
      - framework-db
      - framework-redis

  framework-db:
    container_name: framework-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: FrameworkTest
      MYSQL_ROOT_PASSWORD: f10ygs87

  framework-redis:
    container_name: framework-redis
    image: redis
